### ISSUE TITLE
Please release a patch version

### ISSUE THREAD

**Issue by quite** [StalkR/goircbot#24]
To pick up the last commit

_Originally posted by @quite in https://github.com/StalkR/goircbot/pull/23#issuecomment-566962062_

**Comment by StalkR** [comment]
Thanks for the reminder, done:

```
$ git tag v1.0.1
$ git push origin v1.0.1
Total 0 (delta 0), reused 0 (delta 0)
To github.com:StalkR/goircbot.git
 * [new tag]         v1.0.1 -> v1.0.1
```

https://github.com/StalkR/goircbot/releases
